local missile_manager = require "game.missile.missile_manager"

local msg_touch = hash("touch")

function init(self)
    msg.post(".", "acquire_input_focus")
end

local function fire_missile(pos_x,pos_y)
	if go.get("/main#script", "is_playing") == true then
		missile_manager.add_missile(pos_x,pos_y)
	end
end


function on_input(self, action_id, action)
    if action_id == msg_touch then
    	if action.released == true then fire_missile(action.x,action.y) end
    end
end	
