function init(self)
    particlefx.play("#fx")
    go.animate(".", "rotation.x", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_LINEAR, 0.01, 1, function() go.delete() end)
end

function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Remove this function if not needed
end

